development:
  RAILS_ENV:                development
  DATABASE_URL:             postgres://pawel@localhost/zena

production:
  RAILS_ENV:                production
  DATABASE_URL:             postgres://zen:wSDFGHWLAekjfeorjgu234kjdlfn@localhost/zen
